services:
  app:
    build:
      no_cache: true
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - default
    restart: always
  db:
    hostname: mysql-db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE : fastapi
    networks:
      - default
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
networks:
  default:
    driver: bridge
