services:
  app:
    build:
      no_cache: true
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - default
    restart: always
  db:
    hostname: mysql-db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE : fastapi
    networks:
      - default
networks:
  default:
    driver: bridge
